"""empty message

Revision ID: 0fd0af45760d
Revises: 
Create Date: 2022-06-08 14:50:11.893530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fd0af45760d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['admin_user.id'], )
    )
    op.drop_index('id', table_name='senior_secondary')
    op.drop_table('senior_secondary')
    op.drop_index('id', table_name='junior_secondary')
    op.drop_table('junior_secondary')
    op.drop_index('id', table_name='transaction')
    op.drop_table('transaction')
    op.drop_index('email', table_name='user')
    op.drop_index('id', table_name='user')
    op.drop_index('username', table_name='user')
    op.drop_table('user')
    op.drop_table('admin')
    op.drop_index('id', table_name='university')
    op.drop_table('university')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('question', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.Column('correct_option', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.Column('wrong_option1', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.Column('wrong_option2', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.Column('wrong_option3', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.Column('wrong_option4', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'university', ['id'], unique=False)
    op.create_table('admin',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('address', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=True),
    sa.Column('city', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True),
    sa.Column('state', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True),
    sa.Column('country', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True),
    sa.Column('password', sa.BLOB(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user', ['username'], unique=False)
    op.create_index('id', 'user', ['id'], unique=False)
    op.create_index('email', 'user', ['email'], unique=False)
    op.create_table('transaction',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8_unicode_ci', length=10), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('reference', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('payment_option', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='transaction_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'transaction', ['id'], unique=False)
    op.create_table('junior_secondary',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('question', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.Column('correct_option', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.Column('wrong_option1', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.Column('wrong_option2', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.Column('wrong_option3', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.Column('wrong_option4', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'junior_secondary', ['id'], unique=False)
    op.create_table('senior_secondary',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('question', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.Column('correct_option', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.Column('wrong_option1', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.Column('wrong_option2', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.Column('wrong_option3', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.Column('wrong_option4', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'senior_secondary', ['id'], unique=False)
    op.drop_table('roles_users')
    op.drop_table('role')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
