"""empty message

Revision ID: 01886b637020
Revises: 3dbe4626ccf2
Create Date: 2022-06-17 13:57:45.991168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01886b637020'
down_revision = '3dbe4626ccf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('two_char', sa.String(length=10), nullable=False))
    op.add_column('countries', sa.Column('three_char', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'three_char')
    op.drop_column('countries', 'two_char')
    # ### end Alembic commands ###
