"""empty message

Revision ID: 080af663964e
Revises: b30d127c7fb4
Create Date: 2022-06-30 14:59:27.353665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '080af663964e'
down_revision = 'b30d127c7fb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'role')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('admin', sa.Column('role', mysql.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###
