"""empty message

Revision ID: 081dea815a1e
Revises: 01886b637020
Create Date: 2022-06-17 14:17:49.780590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081dea815a1e'
down_revision = '01886b637020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(length=13), nullable=True))
    op.create_unique_constraint(None, 'user', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
