"""empty message

Revision ID: 0b20dce4a5a9
Revises: 6b8f0cd617e6
Create Date: 2022-06-25 22:26:56.024662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b20dce4a5a9'
down_revision = '6b8f0cd617e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('primary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=250), nullable=False),
    sa.Column('correct_option', sa.String(length=250), nullable=False),
    sa.Column('wrong_option1', sa.String(length=250), nullable=False),
    sa.Column('wrong_option2', sa.String(length=250), nullable=False),
    sa.Column('wrong_option3', sa.String(length=250), nullable=False),
    sa.Column('wrong_option4', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('primary')
    # ### end Alembic commands ###
