"""empty message

Revision ID: 1bc239763504
Revises: 338a5e186bf8
Create Date: 2022-07-04 14:20:38.562415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bc239763504'
down_revision = '338a5e186bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'has_role')
    op.drop_column('user', 'has_role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_role', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('admin', sa.Column('has_role', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
