"""empty message

Revision ID: 281695d22dfa
Revises: 877304b28fba
Create Date: 2022-06-29 16:19:47.921638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281695d22dfa'
down_revision = '877304b28fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdraw', sa.Column('account_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdraw', 'account_number')
    # ### end Alembic commands ###
