"""empty message

Revision ID: 2c71c22e92dd
Revises: 4d46e690c698
Create Date: 2022-06-20 16:45:40.235924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c71c22e92dd'
down_revision = '4d46e690c698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('paid_at', sa.DateTime(), nullable=False))
    op.add_column('deposit', sa.Column('payment_option', sa.String(length=50), nullable=False))
    op.add_column('deposit', sa.Column('currency', sa.String(length=3), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deposit', 'currency')
    op.drop_column('deposit', 'payment_option')
    op.drop_column('deposit', 'paid_at')
    # ### end Alembic commands ###
