"""empty message

Revision ID: 4d46e690c698
Revises: 2cc7006aa2b3
Create Date: 2022-06-20 16:41:06.327263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d46e690c698'
down_revision = '2cc7006aa2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('deposit', sa.Column('attempts', sa.Integer(), nullable=True))
    op.drop_column('deposit', 'payment_option')
    op.drop_column('deposit', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('date', mysql.DATETIME(), nullable=True))
    op.add_column('deposit', sa.Column('payment_option', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('deposit', 'attempts')
    op.drop_column('deposit', 'created_at')
    # ### end Alembic commands ###
