"""empty message

Revision ID: 4f3b848e27f2
Revises: 04b5ee7997ce
Create Date: 2022-06-26 17:42:22.886324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3b848e27f2'
down_revision = '04b5ee7997ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('admin', sa.Column('phone', sa.String(length=13), nullable=True))
    op.add_column('admin', sa.Column('address', sa.String(length=250), nullable=True))
    op.add_column('admin', sa.Column('site_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'site_name')
    op.drop_column('admin', 'address')
    op.drop_column('admin', 'phone')
    op.drop_column('admin', 'email')
    # ### end Alembic commands ###
