"""empty message

Revision ID: 573847c9cdc9
Revises: 9e5ce1d01f4a
Create Date: 2022-07-01 22:25:16.543410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '573847c9cdc9'
down_revision = '9e5ce1d01f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roles_users_ibfk_3', 'roles_users', type_='foreignkey')
    op.drop_column('roles_users', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles_users', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('roles_users_ibfk_3', 'roles_users', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
