"""empty message

Revision ID: 5aca326e6310
Revises: 080af663964e
Create Date: 2022-06-30 14:59:51.763632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aca326e6310'
down_revision = '080af663964e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('role', sa.String(length=10), nullable=False, default='admin'))
    op.add_column('user', sa.Column('role', sa.String(length=10), nullable=False, default='user'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_column('admin', 'role')
    # ### end Alembic commands ###
