"""empty message

Revision ID: 5cd1613e841b
Revises: f10992f2f463
Create Date: 2022-06-21 14:40:18.586611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5cd1613e841b'
down_revision = 'f10992f2f463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdraw', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('withdraw', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdraw', sa.Column('date', mysql.DATETIME(), nullable=True))
    op.drop_column('withdraw', 'created_at')
    # ### end Alembic commands ###
