"""empty message

Revision ID: 5d26d8e09245
Revises: 081dea815a1e
Create Date: 2022-06-17 14:18:37.718062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d26d8e09245'
down_revision = '081dea815a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('phone', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('phone', 'user', ['phone'], unique=False)
    # ### end Alembic commands ###
