"""empty message

Revision ID: 60aaf6dede56
Revises: e85340b20e7c
Create Date: 2022-07-01 21:16:11.653123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60aaf6dede56'
down_revision = 'e85340b20e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('has_role', sa.String(length=10), nullable=False))
    op.drop_column('admin', 'role')
    op.add_column('user', sa.Column('has_role', sa.String(length=10), nullable=False))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', mysql.VARCHAR(length=10), nullable=False))
    op.drop_column('user', 'has_role')
    op.add_column('admin', sa.Column('role', mysql.VARCHAR(length=10), nullable=False))
    op.drop_column('admin', 'has_role')
    # ### end Alembic commands ###
