"""empty message

Revision ID: 6b8f0cd617e6
Revises: 97d1687f0dbf
Create Date: 2022-06-25 18:44:55.192983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8f0cd617e6'
down_revision = '97d1687f0dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdraw', sa.Column('bank_name', sa.String(length=100), nullable=False))
    op.add_column('withdraw', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('withdraw', sa.Column('last_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdraw', 'last_name')
    op.drop_column('withdraw', 'first_name')
    op.drop_column('withdraw', 'bank_name')
    # ### end Alembic commands ###
