"""empty message

Revision ID: 6fc0dcea7627
Revises: 573847c9cdc9
Create Date: 2022-07-03 11:14:46.931762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc0dcea7627'
down_revision = '573847c9cdc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles_users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_column('roles_users', 'user_id')
    # ### end Alembic commands ###
