"""empty message

Revision ID: 855007c640ac
Revises: d38b09cbbff2
Create Date: 2022-06-29 22:51:15.258157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855007c640ac'
down_revision = 'd38b09cbbff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdraw', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('withdraw', sa.Column('bank_name', sa.String(length=100), nullable=False))
    op.add_column('withdraw', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('withdraw', sa.Column('account_number', sa.Integer(), nullable=False))
    op.add_column('withdraw', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('withdraw', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'withdraw', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'withdraw', type_='foreignkey')
    op.drop_column('withdraw', 'user_id')
    op.drop_column('withdraw', 'last_name')
    op.drop_column('withdraw', 'account_number')
    op.drop_column('withdraw', 'first_name')
    op.drop_column('withdraw', 'bank_name')
    op.drop_column('withdraw', 'created_at')
    # ### end Alembic commands ###
