"""empty message

Revision ID: 877304b28fba
Revises: f677ef5d2b3e
Create Date: 2022-06-29 11:16:54.025667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877304b28fba'
down_revision = 'f677ef5d2b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grand_winner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grand_winner', sa.String(50), nullable=True, default=None),
    sa.Column('grand_winner_time', sa.DateTime(), nullable=True, default=None),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grand_winner')
    # ### end Alembic commands ###
