"""empty message

Revision ID: a43a764986d2
Revises: 
Create Date: 2022-07-07 09:48:23.650630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43a764986d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('two_char', sa.String(length=10), nullable=False),
    sa.Column('three_char', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('grand_winner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grand_winner', sa.String(length=50), nullable=True),
    sa.Column('grand_winner_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('junior_secondary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=250), nullable=False),
    sa.Column('correct_option', sa.String(length=250), nullable=False),
    sa.Column('wrong_option1', sa.String(length=250), nullable=False),
    sa.Column('wrong_option2', sa.String(length=250), nullable=False),
    sa.Column('wrong_option3', sa.String(length=250), nullable=False),
    sa.Column('wrong_option4', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('primary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=250), nullable=False),
    sa.Column('correct_option', sa.String(length=250), nullable=False),
    sa.Column('wrong_option1', sa.String(length=250), nullable=False),
    sa.Column('wrong_option2', sa.String(length=250), nullable=False),
    sa.Column('wrong_option3', sa.String(length=250), nullable=False),
    sa.Column('wrong_option4', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('senior_secondary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=250), nullable=False),
    sa.Column('correct_option', sa.String(length=250), nullable=False),
    sa.Column('wrong_option1', sa.String(length=250), nullable=False),
    sa.Column('wrong_option2', sa.String(length=250), nullable=False),
    sa.Column('wrong_option3', sa.String(length=250), nullable=False),
    sa.Column('wrong_option4', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_withdraw', sa.Integer(), nullable=True),
    sa.Column('cost_per_slot', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('site_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('university',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=250), nullable=False),
    sa.Column('correct_option', sa.String(length=250), nullable=False),
    sa.Column('wrong_option1', sa.String(length=250), nullable=False),
    sa.Column('wrong_option2', sa.String(length=250), nullable=False),
    sa.Column('wrong_option3', sa.String(length=250), nullable=False),
    sa.Column('wrong_option4', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('verify', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_correct', sa.Integer(), nullable=True),
    sa.Column('total_failed', sa.Integer(), nullable=True),
    sa.Column('total_attempted', sa.Integer(), nullable=True),
    sa.Column('slots', sa.Integer(), nullable=True),
    sa.Column('coin_balance', sa.Integer(), nullable=True),
    sa.Column('wallet_balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_selection', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('deposit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('payment_option', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('head_shot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('withdraw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdraw')
    op.drop_table('roles_users')
    op.drop_table('head_shot')
    op.drop_table('deposit')
    op.drop_table('attempt')
    op.drop_table('account')
    op.drop_table('user')
    op.drop_table('university')
    op.drop_table('site_settings')
    op.drop_table('senior_secondary')
    op.drop_table('role')
    op.drop_table('primary')
    op.drop_table('levels')
    op.drop_table('junior_secondary')
    op.drop_table('grand_winner')
    op.drop_table('countries')
    # ### end Alembic commands ###
