"""empty message

Revision ID: b1111204c728
Revises: ce5df113c8a7
Create Date: 2022-07-04 11:53:37.181332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1111204c728'
down_revision = 'ce5df113c8a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_role', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_role')
    # ### end Alembic commands ###
