"""empty message

Revision ID: b685f3567a39
Revises: 4f3b848e27f2
Create Date: 2022-06-28 18:25:26.666391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b685f3567a39'
down_revision = '4f3b848e27f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('grand_winner', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'grand_winner')
    # ### end Alembic commands ###
