"""empty message

Revision ID: c0dc9f19f27a
Revises: 0b20dce4a5a9
Create Date: 2022-06-26 01:22:27.337647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0dc9f19f27a'
down_revision = '0b20dce4a5a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verify', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_column('user', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('user', 'status')
    op.drop_column('user', 'verify')
    # ### end Alembic commands ###
