"""empty message

Revision ID: c5a568067b21
Revises: b685f3567a39
Create Date: 2022-06-28 18:54:28.120091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a568067b21'
down_revision = 'b685f3567a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('grand_winner_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'grand_winner_time')
    # ### end Alembic commands ###
