"""empty message

Revision ID: ce5df113c8a7
Revises: 6fc0dcea7627
Create Date: 2022-07-04 09:59:41.403310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce5df113c8a7'
down_revision = '6fc0dcea7627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('has_role', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'has_role')
    # ### end Alembic commands ###
