"""empty message

Revision ID: cf05200b9cf3
Revises: 60d6c2bf4eab
Create Date: 2022-06-16 22:44:29.177549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf05200b9cf3'
down_revision = '60d6c2bf4eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles_users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_column('roles_users', 'user_id')
    # ### end Alembic commands ###
