"""empty message

Revision ID: d38b09cbbff2
Revises: 281695d22dfa
Create Date: 2022-06-29 22:46:04.052154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd38b09cbbff2'
down_revision = '281695d22dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('withdraw_ibfk_1', 'withdraw', type_='foreignkey')
    op.drop_column('withdraw', 'first_name')
    op.drop_column('withdraw', 'account_number')
    op.drop_column('withdraw', 'bank_name')
    op.drop_column('withdraw', 'last_name')
    op.drop_column('withdraw', 'created_at')
    op.drop_column('withdraw', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdraw', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('withdraw', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('withdraw', sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('withdraw', sa.Column('bank_name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('withdraw', sa.Column('account_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('withdraw', sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False))
    op.create_foreign_key('withdraw_ibfk_1', 'withdraw', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
