"""empty message

Revision ID: de4280a78122
Revises: 855007c640ac
Create Date: 2022-06-30 14:56:06.022183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de4280a78122'
down_revision = '855007c640ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('role', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('role', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_column('admin', 'role')
    # ### end Alembic commands ###
