"""empty message

Revision ID: f19fb61290a0
Revises: 975d99286182
Create Date: 2022-06-23 18:26:38.082964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19fb61290a0'
down_revision = '975d99286182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('cost_per_slot', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'cost_per_slot')
    # ### end Alembic commands ###
