"""empty message

Revision ID: f677ef5d2b3e
Revises: c5a568067b21
Create Date: 2022-06-29 11:12:47.261728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f677ef5d2b3e'
down_revision = 'c5a568067b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'grand_winner')
    op.drop_column('admin', 'grand_winner_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('grand_winner_time', mysql.DATETIME(), nullable=True))
    op.add_column('admin', sa.Column('grand_winner', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
